version: '3'
services:
  app:
    build: .
    ports:
      - "9999:9999"
    depends_on:
      - mongodb
      - redis
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=easybackend
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"

  redis:
    image: redis:latest
    ports:
      - "6380:6379"